
pipeline {

    agent {
        kubernetes {
      yaml """
apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins-pipelines
  containers:
  - name: terraform-1-0-6
    image: hashicorp/terraform:1.0.6
    command:
    - cat
    tty: true
  nodeSelector:
    node.kubernetes.io/lifecycle: spot
  tolerations:
    - key: lifecycle
      operator: Equal
      value: spot
      effect: NoSchedule  
"""
        }
    }
    stages {
        stage('Terraform Validate') {
            steps {
                container('terraform-1-0-6') {
                    dir('deploy') {
                        echo '*** Initializing Terraform ***'
                        sh "terraform init -no-color -backend=false"
                        echo '*** Validating Terraform Code***'
                        sh "terraform validate"
                    }
                }
            }
        }
    }
}
