
pipeline {

    agent {
        kubernetes {
      yaml """
apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins-service-account  
  containers:
  - name: terraform-1-0-6
    image: hashicorp/terraform:1.0.6
    command:
    - cat
    tty: true 
"""
        }
    }
    stages {
        stage('Terraform Validate') {
            steps {
                container('terraform-1-0-6') {
                    dir('terraform') {
                        echo '*** Initializing Terraform ***'
                        sh "terraform init -no-color -backend=false"
                        echo '*** Validating Terraform Code***'
                        sh "terraform validate"
                    }
                }
            }
        }
        stage('Terraform apply') {
            steps {
                container('terraform-1-0-6') {
                    dir('terraform') {
                        echo '*** Initializing Terraform ***'
                        sh "terraform plan -out=plannew"
                        echo '*** Validating Terraform Code***'
                        sh "terraform apply 'plannew'"
                    }
                }
            }
        }
    }
}
