apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Options: ReadWriteOnce, ReadOnlyMany, ReadWriteMany
  resources:
    requests:
      storage: {{.Values.pvc.storage}}  # Storage size requested
  storageClassName: {{.Values.pvc.storageclass}}  # Optional: Use specific StorageClass
